/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RRoomIdRouteImport } from './routes/r.$roomId'
import { Route as ApiLiveblocksAuthRouteImport } from './routes/api/liveblocks-auth'
import { Route as ApiGenerateArtifactsRouteImport } from './routes/api/generate-artifacts'
import { Route as ApiCanvasOpsRouteImport } from './routes/api/canvas-ops'
import { Route as ApiElevenlabsScribeTokenRouteImport } from './routes/api/elevenlabs/scribe-token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RRoomIdRoute = RRoomIdRouteImport.update({
  id: '/r/$roomId',
  path: '/r/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveblocksAuthRoute = ApiLiveblocksAuthRouteImport.update({
  id: '/api/liveblocks-auth',
  path: '/api/liveblocks-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateArtifactsRoute = ApiGenerateArtifactsRouteImport.update({
  id: '/api/generate-artifacts',
  path: '/api/generate-artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCanvasOpsRoute = ApiCanvasOpsRouteImport.update({
  id: '/api/canvas-ops',
  path: '/api/canvas-ops',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiElevenlabsScribeTokenRoute =
  ApiElevenlabsScribeTokenRouteImport.update({
    id: '/api/elevenlabs/scribe-token',
    path: '/api/elevenlabs/scribe-token',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/canvas-ops': typeof ApiCanvasOpsRoute
  '/api/generate-artifacts': typeof ApiGenerateArtifactsRoute
  '/api/liveblocks-auth': typeof ApiLiveblocksAuthRoute
  '/r/$roomId': typeof RRoomIdRoute
  '/api/elevenlabs/scribe-token': typeof ApiElevenlabsScribeTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/canvas-ops': typeof ApiCanvasOpsRoute
  '/api/generate-artifacts': typeof ApiGenerateArtifactsRoute
  '/api/liveblocks-auth': typeof ApiLiveblocksAuthRoute
  '/r/$roomId': typeof RRoomIdRoute
  '/api/elevenlabs/scribe-token': typeof ApiElevenlabsScribeTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/canvas-ops': typeof ApiCanvasOpsRoute
  '/api/generate-artifacts': typeof ApiGenerateArtifactsRoute
  '/api/liveblocks-auth': typeof ApiLiveblocksAuthRoute
  '/r/$roomId': typeof RRoomIdRoute
  '/api/elevenlabs/scribe-token': typeof ApiElevenlabsScribeTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/canvas-ops'
    | '/api/generate-artifacts'
    | '/api/liveblocks-auth'
    | '/r/$roomId'
    | '/api/elevenlabs/scribe-token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/canvas-ops'
    | '/api/generate-artifacts'
    | '/api/liveblocks-auth'
    | '/r/$roomId'
    | '/api/elevenlabs/scribe-token'
  id:
    | '__root__'
    | '/'
    | '/api/canvas-ops'
    | '/api/generate-artifacts'
    | '/api/liveblocks-auth'
    | '/r/$roomId'
    | '/api/elevenlabs/scribe-token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCanvasOpsRoute: typeof ApiCanvasOpsRoute
  ApiGenerateArtifactsRoute: typeof ApiGenerateArtifactsRoute
  ApiLiveblocksAuthRoute: typeof ApiLiveblocksAuthRoute
  RRoomIdRoute: typeof RRoomIdRoute
  ApiElevenlabsScribeTokenRoute: typeof ApiElevenlabsScribeTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$roomId': {
      id: '/r/$roomId'
      path: '/r/$roomId'
      fullPath: '/r/$roomId'
      preLoaderRoute: typeof RRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/liveblocks-auth': {
      id: '/api/liveblocks-auth'
      path: '/api/liveblocks-auth'
      fullPath: '/api/liveblocks-auth'
      preLoaderRoute: typeof ApiLiveblocksAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-artifacts': {
      id: '/api/generate-artifacts'
      path: '/api/generate-artifacts'
      fullPath: '/api/generate-artifacts'
      preLoaderRoute: typeof ApiGenerateArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/canvas-ops': {
      id: '/api/canvas-ops'
      path: '/api/canvas-ops'
      fullPath: '/api/canvas-ops'
      preLoaderRoute: typeof ApiCanvasOpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/elevenlabs/scribe-token': {
      id: '/api/elevenlabs/scribe-token'
      path: '/api/elevenlabs/scribe-token'
      fullPath: '/api/elevenlabs/scribe-token'
      preLoaderRoute: typeof ApiElevenlabsScribeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCanvasOpsRoute: ApiCanvasOpsRoute,
  ApiGenerateArtifactsRoute: ApiGenerateArtifactsRoute,
  ApiLiveblocksAuthRoute: ApiLiveblocksAuthRoute,
  RRoomIdRoute: RRoomIdRoute,
  ApiElevenlabsScribeTokenRoute: ApiElevenlabsScribeTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
