/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DirectionsRouteImport } from './routes/directions'
import { Route as ExamplesRouteImport } from './routes/examples'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ApiCanvasOpsRouteImport } from './routes/api/canvas-ops'
import { Route as ApiCartoonistDrawRouteImport } from './routes/api/cartoonist-draw'
import { Route as ApiDevilsAdvocateRouteImport } from './routes/api/devils-advocate'
import { Route as ApiGenerateArtifactsRouteImport } from './routes/api/generate-artifacts'
import { Route as ApiInferInsightsRouteImport } from './routes/api/infer-insights'
import { Route as ApiLiveblocksAuthRouteImport } from './routes/api/liveblocks-auth'
import { Route as ApiMediatorTtsRouteImport } from './routes/api/mediator-tts'
import { Route as ApiParseIntroRouteImport } from './routes/api/parse-intro'
import { Route as ApiSessionRecapRouteImport } from './routes/api/session-recap'
import { Route as ApiSessionSummaryRouteImport } from './routes/api/session-summary'
import { Route as ApiTranscribeChunkRouteImport } from './routes/api/transcribe-chunk'
import { Route as ApiTranscribeSampleRouteImport } from './routes/api/transcribe-sample'
import { Route as RRoomIdRouteImport } from './routes/r.$roomId'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions.$sessionId'
import { Route as SessionsNewRouteImport } from './routes/sessions.new'
import { Route as ApiElevenlabsScribeTokenRouteImport } from './routes/api/elevenlabs/scribe-token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectionsRoute = DirectionsRouteImport.update({
  id: '/directions',
  path: '/directions',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesRoute = ExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCanvasOpsRoute = ApiCanvasOpsRouteImport.update({
  id: '/api/canvas-ops',
  path: '/api/canvas-ops',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCartoonistDrawRoute = ApiCartoonistDrawRouteImport.update({
  id: '/api/cartoonist-draw',
  path: '/api/cartoonist-draw',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevilsAdvocateRoute = ApiDevilsAdvocateRouteImport.update({
  id: '/api/devils-advocate',
  path: '/api/devils-advocate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateArtifactsRoute = ApiGenerateArtifactsRouteImport.update({
  id: '/api/generate-artifacts',
  path: '/api/generate-artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInferInsightsRoute = ApiInferInsightsRouteImport.update({
  id: '/api/infer-insights',
  path: '/api/infer-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveblocksAuthRoute = ApiLiveblocksAuthRouteImport.update({
  id: '/api/liveblocks-auth',
  path: '/api/liveblocks-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediatorTtsRoute = ApiMediatorTtsRouteImport.update({
  id: '/api/mediator-tts',
  path: '/api/mediator-tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiParseIntroRoute = ApiParseIntroRouteImport.update({
  id: '/api/parse-intro',
  path: '/api/parse-intro',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionRecapRoute = ApiSessionRecapRouteImport.update({
  id: '/api/session-recap',
  path: '/api/session-recap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionSummaryRoute = ApiSessionSummaryRouteImport.update({
  id: '/api/session-summary',
  path: '/api/session-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeChunkRoute = ApiTranscribeChunkRouteImport.update({
  id: '/api/transcribe-chunk',
  path: '/api/transcribe-chunk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeSampleRoute = ApiTranscribeSampleRouteImport.update({
  id: '/api/transcribe-sample',
  path: '/api/transcribe-sample',
  getParentRoute: () => rootRouteImport,
} as any)
const RRoomIdRoute = RRoomIdRouteImport.update({
  id: '/r/$roomId',
  path: '/r/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsNewRoute = SessionsNewRouteImport.update({
  id: '/sessions/new',
  path: '/sessions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiElevenlabsScribeTokenRoute =
  ApiElevenlabsScribeTokenRouteImport.update({
    id: '/api/elevenlabs/scribe-token',
    path: '/api/elevenlabs/scribe-token',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/directions': typeof DirectionsRoute
  '/examples': typeof ExamplesRoute
  '/onboarding': typeof OnboardingRoute
  '/api/canvas-ops': typeof ApiCanvasOpsRoute
  '/api/cartoonist-draw': typeof ApiCartoonistDrawRoute
  '/api/devils-advocate': typeof ApiDevilsAdvocateRoute
  '/api/generate-artifacts': typeof ApiGenerateArtifactsRoute
  '/api/infer-insights': typeof ApiInferInsightsRoute
  '/api/liveblocks-auth': typeof ApiLiveblocksAuthRoute
  '/api/mediator-tts': typeof ApiMediatorTtsRoute
  '/api/parse-intro': typeof ApiParseIntroRoute
  '/api/session-recap': typeof ApiSessionRecapRoute
  '/api/session-summary': typeof ApiSessionSummaryRoute
  '/api/transcribe-chunk': typeof ApiTranscribeChunkRoute
  '/api/transcribe-sample': typeof ApiTranscribeSampleRoute
  '/r/$roomId': typeof RRoomIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/sessions/new': typeof SessionsNewRoute
  '/api/elevenlabs/scribe-token': typeof ApiElevenlabsScribeTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/directions': typeof DirectionsRoute
  '/examples': typeof ExamplesRoute
  '/onboarding': typeof OnboardingRoute
  '/api/canvas-ops': typeof ApiCanvasOpsRoute
  '/api/cartoonist-draw': typeof ApiCartoonistDrawRoute
  '/api/devils-advocate': typeof ApiDevilsAdvocateRoute
  '/api/generate-artifacts': typeof ApiGenerateArtifactsRoute
  '/api/infer-insights': typeof ApiInferInsightsRoute
  '/api/liveblocks-auth': typeof ApiLiveblocksAuthRoute
  '/api/mediator-tts': typeof ApiMediatorTtsRoute
  '/api/parse-intro': typeof ApiParseIntroRoute
  '/api/session-recap': typeof ApiSessionRecapRoute
  '/api/session-summary': typeof ApiSessionSummaryRoute
  '/api/transcribe-chunk': typeof ApiTranscribeChunkRoute
  '/api/transcribe-sample': typeof ApiTranscribeSampleRoute
  '/r/$roomId': typeof RRoomIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/sessions/new': typeof SessionsNewRoute
  '/api/elevenlabs/scribe-token': typeof ApiElevenlabsScribeTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/directions': typeof DirectionsRoute
  '/examples': typeof ExamplesRoute
  '/onboarding': typeof OnboardingRoute
  '/api/canvas-ops': typeof ApiCanvasOpsRoute
  '/api/cartoonist-draw': typeof ApiCartoonistDrawRoute
  '/api/devils-advocate': typeof ApiDevilsAdvocateRoute
  '/api/generate-artifacts': typeof ApiGenerateArtifactsRoute
  '/api/infer-insights': typeof ApiInferInsightsRoute
  '/api/liveblocks-auth': typeof ApiLiveblocksAuthRoute
  '/api/mediator-tts': typeof ApiMediatorTtsRoute
  '/api/parse-intro': typeof ApiParseIntroRoute
  '/api/session-recap': typeof ApiSessionRecapRoute
  '/api/session-summary': typeof ApiSessionSummaryRoute
  '/api/transcribe-chunk': typeof ApiTranscribeChunkRoute
  '/api/transcribe-sample': typeof ApiTranscribeSampleRoute
  '/r/$roomId': typeof RRoomIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/sessions/new': typeof SessionsNewRoute
  '/api/elevenlabs/scribe-token': typeof ApiElevenlabsScribeTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/directions'
    | '/examples'
    | '/onboarding'
    | '/api/canvas-ops'
    | '/api/cartoonist-draw'
    | '/api/devils-advocate'
    | '/api/generate-artifacts'
    | '/api/infer-insights'
    | '/api/liveblocks-auth'
    | '/api/mediator-tts'
    | '/api/parse-intro'
    | '/api/session-recap'
    | '/api/session-summary'
    | '/api/transcribe-chunk'
    | '/api/transcribe-sample'
    | '/r/$roomId'
    | '/sessions/$sessionId'
    | '/sessions/new'
    | '/api/elevenlabs/scribe-token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/directions'
    | '/examples'
    | '/onboarding'
    | '/api/canvas-ops'
    | '/api/cartoonist-draw'
    | '/api/devils-advocate'
    | '/api/generate-artifacts'
    | '/api/infer-insights'
    | '/api/liveblocks-auth'
    | '/api/mediator-tts'
    | '/api/parse-intro'
    | '/api/session-recap'
    | '/api/session-summary'
    | '/api/transcribe-chunk'
    | '/api/transcribe-sample'
    | '/r/$roomId'
    | '/sessions/$sessionId'
    | '/sessions/new'
    | '/api/elevenlabs/scribe-token'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/directions'
    | '/examples'
    | '/onboarding'
    | '/api/canvas-ops'
    | '/api/cartoonist-draw'
    | '/api/devils-advocate'
    | '/api/generate-artifacts'
    | '/api/infer-insights'
    | '/api/liveblocks-auth'
    | '/api/mediator-tts'
    | '/api/parse-intro'
    | '/api/session-recap'
    | '/api/session-summary'
    | '/api/transcribe-chunk'
    | '/api/transcribe-sample'
    | '/r/$roomId'
    | '/sessions/$sessionId'
    | '/sessions/new'
    | '/api/elevenlabs/scribe-token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DirectionsRoute: typeof DirectionsRoute
  ExamplesRoute: typeof ExamplesRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiCanvasOpsRoute: typeof ApiCanvasOpsRoute
  ApiCartoonistDrawRoute: typeof ApiCartoonistDrawRoute
  ApiDevilsAdvocateRoute: typeof ApiDevilsAdvocateRoute
  ApiGenerateArtifactsRoute: typeof ApiGenerateArtifactsRoute
  ApiInferInsightsRoute: typeof ApiInferInsightsRoute
  ApiLiveblocksAuthRoute: typeof ApiLiveblocksAuthRoute
  ApiMediatorTtsRoute: typeof ApiMediatorTtsRoute
  ApiParseIntroRoute: typeof ApiParseIntroRoute
  ApiSessionRecapRoute: typeof ApiSessionRecapRoute
  ApiSessionSummaryRoute: typeof ApiSessionSummaryRoute
  ApiTranscribeChunkRoute: typeof ApiTranscribeChunkRoute
  ApiTranscribeSampleRoute: typeof ApiTranscribeSampleRoute
  RRoomIdRoute: typeof RRoomIdRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  SessionsNewRoute: typeof SessionsNewRoute
  ApiElevenlabsScribeTokenRoute: typeof ApiElevenlabsScribeTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directions': {
      id: '/directions'
      path: '/directions'
      fullPath: '/directions'
      preLoaderRoute: typeof DirectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples': {
      id: '/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/canvas-ops': {
      id: '/api/canvas-ops'
      path: '/api/canvas-ops'
      fullPath: '/api/canvas-ops'
      preLoaderRoute: typeof ApiCanvasOpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cartoonist-draw': {
      id: '/api/cartoonist-draw'
      path: '/api/cartoonist-draw'
      fullPath: '/api/cartoonist-draw'
      preLoaderRoute: typeof ApiCartoonistDrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/devils-advocate': {
      id: '/api/devils-advocate'
      path: '/api/devils-advocate'
      fullPath: '/api/devils-advocate'
      preLoaderRoute: typeof ApiDevilsAdvocateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-artifacts': {
      id: '/api/generate-artifacts'
      path: '/api/generate-artifacts'
      fullPath: '/api/generate-artifacts'
      preLoaderRoute: typeof ApiGenerateArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/infer-insights': {
      id: '/api/infer-insights'
      path: '/api/infer-insights'
      fullPath: '/api/infer-insights'
      preLoaderRoute: typeof ApiInferInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/liveblocks-auth': {
      id: '/api/liveblocks-auth'
      path: '/api/liveblocks-auth'
      fullPath: '/api/liveblocks-auth'
      preLoaderRoute: typeof ApiLiveblocksAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mediator-tts': {
      id: '/api/mediator-tts'
      path: '/api/mediator-tts'
      fullPath: '/api/mediator-tts'
      preLoaderRoute: typeof ApiMediatorTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/parse-intro': {
      id: '/api/parse-intro'
      path: '/api/parse-intro'
      fullPath: '/api/parse-intro'
      preLoaderRoute: typeof ApiParseIntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session-recap': {
      id: '/api/session-recap'
      path: '/api/session-recap'
      fullPath: '/api/session-recap'
      preLoaderRoute: typeof ApiSessionRecapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session-summary': {
      id: '/api/session-summary'
      path: '/api/session-summary'
      fullPath: '/api/session-summary'
      preLoaderRoute: typeof ApiSessionSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe-chunk': {
      id: '/api/transcribe-chunk'
      path: '/api/transcribe-chunk'
      fullPath: '/api/transcribe-chunk'
      preLoaderRoute: typeof ApiTranscribeChunkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe-sample': {
      id: '/api/transcribe-sample'
      path: '/api/transcribe-sample'
      fullPath: '/api/transcribe-sample'
      preLoaderRoute: typeof ApiTranscribeSampleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$roomId': {
      id: '/r/$roomId'
      path: '/r/$roomId'
      fullPath: '/r/$roomId'
      preLoaderRoute: typeof RRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/new': {
      id: '/sessions/new'
      path: '/sessions/new'
      fullPath: '/sessions/new'
      preLoaderRoute: typeof SessionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/elevenlabs/scribe-token': {
      id: '/api/elevenlabs/scribe-token'
      path: '/api/elevenlabs/scribe-token'
      fullPath: '/api/elevenlabs/scribe-token'
      preLoaderRoute: typeof ApiElevenlabsScribeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DirectionsRoute: DirectionsRoute,
  ExamplesRoute: ExamplesRoute,
  OnboardingRoute: OnboardingRoute,
  ApiCanvasOpsRoute: ApiCanvasOpsRoute,
  ApiCartoonistDrawRoute: ApiCartoonistDrawRoute,
  ApiDevilsAdvocateRoute: ApiDevilsAdvocateRoute,
  ApiGenerateArtifactsRoute: ApiGenerateArtifactsRoute,
  ApiInferInsightsRoute: ApiInferInsightsRoute,
  ApiLiveblocksAuthRoute: ApiLiveblocksAuthRoute,
  ApiMediatorTtsRoute: ApiMediatorTtsRoute,
  ApiParseIntroRoute: ApiParseIntroRoute,
  ApiSessionRecapRoute: ApiSessionRecapRoute,
  ApiSessionSummaryRoute: ApiSessionSummaryRoute,
  ApiTranscribeChunkRoute: ApiTranscribeChunkRoute,
  ApiTranscribeSampleRoute: ApiTranscribeSampleRoute,
  RRoomIdRoute: RRoomIdRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  SessionsNewRoute: SessionsNewRoute,
  ApiElevenlabsScribeTokenRoute: ApiElevenlabsScribeTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
